### PR TITLE
replaced tns-core-modules by @nativescript/core and added some fixes

### PR DESCRIPTION
**Pull request by alexander-mai**
* replaced tns-core-modules by @nativescript/core
* added check for existing webview.ios object by Ken Seah (seahken@3d20a8f)
* added off-handler to nativescript-webview-interface.js by FrogTheFrog (FrogTheFrog@74098fe)
* quote string messages in URL for Android by saulshanabrook (saulshanabrook@a3c27c4)

### CODE REVIEW

**Comment by eltharynd** [comment]
@shripalsoni04 Can you please take this since your repo is the official one on nativescript marketplace?
I've verified his changes myself and it fixed this plugin for new nativescript versions


thanks @alexander-mai for taking the time

**Comment by wendt88** [comment]
@shripalsoni04 can you please accept this PR to add compatibility to NS7?

Thanks!

**Comment by shripalsoni04** [comment]
Sorry, @alexander-mai for taking look at this PR so late. I am actually not working on any nativescript projects since long and was so busy with other stuff. 

Though I haven't tested it personally, the changes seem fine to me. So going to merge it.

Thanks a lot for your contributions. 

cc @eltharynd , @wendt88

**Comment by shripalsoni04** [comment]
Published the changes of this PR with version @1.4.4. Thanks all 🙌

**Pull request merged**
